const mongoose = require("mongoose");

const productSchema = new mongoose.Schema({
  id: String,
  inwardNo: String,
  vehicleNumber: String,
  dateOfShifting: String,
  variety: String,
  type: String,
  species: String,
  size: String,
count: String,
remark: String,
condition: String,
productColour: String,
treatment: String,
freshRp: String,
productSpecification: String,
tapeColour: String,
structure: String,
packingType: String,
packingKg: String,
glaze: String,
bagColour: String,
freezingStyle: String,
freezingType: String,
freezingInstruction: String,
cartonColour: String,
cartonBrand: String,
cartonType: String,
harvestArea: String,
lotNo: String,
poNo: String,
totalCartons: String,
totalKg: String,
productionDate: String,
expiryDate: String,
stockAge: String,
gatePass: String,
loadingStart: String,
loadingEnd: String,
location: String,
palletNo: String,
updatedBy: String,
documentNo: String,
freezingDone: String,
partyName: String,
locationChangeDate: String,
loadingSupervisor: String,
unloadingSupervisor: String,
unloadingStart: String,
unloadingEnd: String,
productTemp: String,

  // minus data
  balanceQty: String,
  balanceKg: String,
  outwardNo: String,
  outDate: String,
  outwardVehicle: String,
  cartons: String,
  remark: String,
  updatedBy: String,
  shipmentPo: String,
shipmentDate: String,
shipmentVehicle: String,
shipmentCont: String,
shipmentOutCarton: String,
shipmentRemark: String,
lessUpdater: String,
}, { timestamps: true });

module.exports = mongoose.model("Product", productSchema);